# Netlify 部署配置
[build]
  # 构建命令
  command = "npm run deploy:static"
  # 发布目录
  publish = ".output/public"

# 环境变量（在 Netlify 控制台中设置）
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# 重定向规则（用于 SPA 路由）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!US"]}

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态文件缓存
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JSON 数据文件缓存
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json"